### ISSUE TITLE
Data not exported to InfluxDB

### ISSUE THREAD

**Issue by esolitos** [avojak/pihole-influxdb-monitor#3]
Hi and thanks for this small piece of software, really appreciated.

I have given it a quick test however I don't see the data exported to InfluxDB. I am not really sure which part is not working, but I don't see any errors in the logs at the least:

![image](https://github.com/avojak/pihole-influxdb-monitor/assets/401819/e26be36c-5765-4caf-bba3-a24feb1d0990)

I have double checked the configuration and it seem correct from what I can see. 🤔 I am running the container using ansible with this setup:
```yaml
- docker_container:
    image: avojak/pihole-influxdb
    name: pihole-influxdb
    env:
      PIHOLE_ALIAS: "pihole"
      PIHOLE_ADDRESS: "http://{{ pihole_net_ip }}"
      PIHOLE_TOKEN: "MySuperS3creTtØK3n"
      INFLUXDB_ADDRESS: "http://{{ influxdb_net_ip }}:8086"
      INFLUXDB_ORG: "h...."
      INFLUXDB_TOKEN: "4nøth3rT0kenH3re=="
      INFLUXDB_BUCKET: "pihole"
```
